version: "3.9"

services:
  nginx-proxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./data/nginx-proxy:/data
      - ./letsencrypt:/etc/letsencrypt

networks:
  npm_network:
    external: true
